import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms and Conditions | ID Photo Maker India",
  description:
    "Terms and conditions for using ID Photo Maker India. Understand your responsibilities, our liability limitations, and the rules governing use of our free photo tools.",
  alternates: { canonical: "/terms-and-conditions" },
};

const EFFECTIVE_DATE = "15 April 2025";

export default function TermsAndConditionsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:py-16">
      {/* Page Header */}
      <div className="mb-10">
        <h1 className="text-3xl font-bold text-[#2563EB] sm:text-4xl">
          Terms and Conditions
        </h1>
        <p className="mt-3 text-sm text-slate-500">
          Effective date: {EFFECTIVE_DATE}
        </p>
        <p className="mt-4 text-lg leading-relaxed text-slate-600">
          By accessing or using ID Photo Maker India, you agree to be bound by
          these Terms and Conditions. Please read them carefully before using
          the platform.
        </p>
      </div>

      <div className="space-y-10">
        {/* 1. Acceptance of Terms */}
        <section>
          <h2 className="text-xl font-bold text-[#111827] sm:text-2xl">
            1. Acceptance of Terms
          </h2>
          <p className="mt-4 text-slate-700 leading-relaxed">
            By using this website and its tools, you confirm that you have read,
            understood, and agree to be bound by these Terms and Conditions and
            our Privacy Policy. If you do not agree, please discontinue use of
            the platform immediately.
          </p>
        </section>

        {/* 2. Usage Terms */}
        <section>
          <h2 className="text-xl font-bold text-[#111827] sm:text-2xl">
            2. Usage Terms
          </h2>
          <div className="mt-4 space-y-3 text-slate-700 leading-relaxed">
            <p>
              The tools and services provided by ID Photo Maker India are
              offered on an{" "}
              <span className="font-semibold text-[#111827]">
                &quot;as-is&quot;
              </span>{" "}
              and{" "}
              <span className="font-semibold text-[#111827]">
                &quot;as-available&quot;
              </span>{" "}
              basis, without warranties of any kind, either express or implied.
            </p>
            <ul className="space-y-3 pl-1">
              {[
                "You are solely responsible for verifying that the photos and signatures you produce meet the current requirements of the relevant government portal or examination authority.",
                "Government portals may update their specifications at any time. Always check the official portal before submitting your application.",
                "You must not use the platform for any unlawful purpose or in any manner inconsistent with these Terms.",
                "You are responsible for ensuring that any photos processed through the platform do not infringe upon the rights of any third party.",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1 shrink-0 text-[#2563EB]">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* 3. Disclaimer of Liability */}
        <section>
          <h2 className="text-xl font-bold text-[#111827] sm:text-2xl">
            3. Disclaimer of Liability
          </h2>
          <div className="mt-4 space-y-4 text-slate-700 leading-relaxed">
            <div className="rounded-lg border border-amber-200 bg-amber-50 px-5 py-4">
              <p className="text-sm text-amber-800 leading-relaxed">
                <span className="font-semibold">Important notice:</span> ID
                Photo Maker India does not guarantee that photos produced using
                our tools will be accepted by any government portal, examination
                board, or official authority. Requirements vary by portal and
                change frequently.
              </p>
            </div>
            <ul className="space-y-3 pl-1">
              {[
                "We make no guarantee that a photo processed through our platform will be accepted by any government body, ministry, or examination authority.",
                "Acceptance of photos is determined solely by the relevant authority based on their current, published requirements.",
                "We are not liable for any application rejection, delay, or loss arising from the use of photos generated by our tools.",
                "We are not affiliated with the Government of India, any state government, or any examination authority. Trademarks and brand names referenced on this platform belong to their respective owners.",
                "We are not liable for any direct, indirect, incidental, or consequential damages arising from your use of or inability to use the platform.",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1 shrink-0 text-[#2563EB]">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* 4. Service Availability */}
        <section>
          <h2 className="text-xl font-bold text-[#111827] sm:text-2xl">
            4. Service Availability and Changes
          </h2>
          <div className="mt-4 space-y-3 text-slate-700 leading-relaxed">
            <p>
              We reserve the right to modify, update, suspend, or discontinue
              any part of the platform at any time without prior notice.
            </p>
            <ul className="space-y-3 pl-1">
              {[
                "Tools and their presets may be updated to reflect new portal requirements, technical improvements, or changes in our service offering.",
                "We do not guarantee uninterrupted or error-free access to the platform.",
                "We may add new tools or remove existing ones at our discretion.",
                "These Terms may be updated from time to time. Continued use of the platform after changes constitutes acceptance of the revised Terms.",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1 shrink-0 text-[#2563EB]">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* 5. Restrictions */}
        <section>
          <h2 className="text-xl font-bold text-[#111827] sm:text-2xl">
            5. Prohibited Use
          </h2>
          <div className="mt-4 space-y-3 text-slate-700 leading-relaxed">
            <p>You agree not to use this platform to:</p>
            <ul className="space-y-3 pl-1">
              {[
                "Upload, process, or distribute any illegal, obscene, defamatory, or otherwise objectionable content.",
                "Attempt to gain unauthorised access to any part of the platform or its underlying infrastructure.",
                "Use automated tools, bots, or scripts to interact with the platform in a manner that disrupts normal service.",
                "Impersonate any person or entity, or misrepresent your identity in any way.",
                "Violate any applicable local, national, or international law or regulation.",
                "Reproduce, copy, or redistribute any part of the platform's code or content without written permission.",
              ].map((item, i) => (
                <li key={i} className="flex gap-3">
                  <span className="mt-1 shrink-0 text-[#2563EB]">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* 6. Intellectual Property */}
        <section>
          <h2 className="text-xl font-bold text-[#111827] sm:text-2xl">
            6. Intellectual Property
          </h2>
          <p className="mt-4 text-slate-700 leading-relaxed">
            All content, design, code, and branding on this platform — unless
            otherwise noted — is the property of ID Photo Maker India. You may
            not reproduce or repurpose any part of this platform without prior
            written consent. Third-party trademarks and logos referenced on this
            site belong to their respective owners and are used solely for
            descriptive purposes.
          </p>
        </section>

        {/* 7. Governing Law */}
        <section>
          <h2 className="text-xl font-bold text-[#111827] sm:text-2xl">
            7. Governing Law
          </h2>
          <p className="mt-4 text-slate-700 leading-relaxed">
            These Terms and Conditions are governed by and construed in
            accordance with the laws of India. Any disputes arising under or in
            connection with these Terms shall be subject to the exclusive
            jurisdiction of the courts of India.
          </p>
        </section>

        {/* 8. Contact */}
        <section>
          <h2 className="text-xl font-bold text-[#111827] sm:text-2xl">
            8. Contact
          </h2>
          <p className="mt-4 text-slate-700 leading-relaxed">
            If you have any questions regarding these Terms and Conditions,
            please contact us via our{" "}
            <a
              href="/contact"
              className="font-medium text-[#2563EB] underline underline-offset-4 hover:text-[#1D4ED8]"
            >
              Contact page
            </a>{" "}
            or email{" "}
            <a
              href="mailto:support@idphotomaker.in"
              className="font-medium text-[#2563EB] underline underline-offset-4 hover:text-[#1D4ED8]"
            >
              support@idphotomaker.in
            </a>
            .
          </p>
        </section>

        {/* Footer note */}
        <p className="rounded-lg border border-slate-200 bg-slate-50 px-5 py-4 text-sm text-slate-600 leading-relaxed">
          By continuing to use ID Photo Maker India, you acknowledge that you
          have read these Terms and Conditions and agree to be bound by them.
          Last updated: {EFFECTIVE_DATE}.
        </p>
      </div>
    </div>
  );
}
